/*
 * REDUX action type constant
*/

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_INFO_FETCHED = 'USER_INFO_FETCHED';
export const STATION_ID_SET = 'STATION_ID_SET';
export const STATION_ACTIVATE_SUCCESS = 'STATION_ACTIVATE_SUCCESS';
export const STATION_ACTIVATE_ERROR = 'STATION_ACTIVATE_ERROR';
export const STATION_CURRENT_UNFINISH_TASK_FETCHED = 'STATION_CURRENT_UNFINISH_TASK_FETCHED';
export const AT_STATION_POD_LAYOUT_INFO_FETCHED = 'AT_STATION_POD_LAYOUT_INFO_FETCHED';
export const SET_STATION_TASK_TYPE = 'SET_STATION_TASK_TYPE';
export const COMING_PODS_FETCHED = 'COMING_PODS_FETCHED';

// OPERATION
export const DEVICE_LIST_FETCHED = 'DEVICE_LIST_FETCHED';
export const SET_HOLDER_SETUP_WAITLIST = 'SET_HOLDER_SETUP_WAITLIST';
export const ADD_BIN_TO_HOLDER = 'ADD_BIN_TO_HOLDER';
export const UNASSIGN_BIN_FROM_HOLDER = 'UNASSIGN_BIN_FROM_HOLDER';
export const SHOW_CHANGE_BIN_MODAL = 'SHOW_CHANGE_BIN_MODAL';
export const UNLINK_ALL_BIN_FROM_HOLDER_SUCCESS = 'UNLINK_ALL_BIN_FROM_HOLDER_SUCCESS';
export const UNLINK_ALL_BIN_FROM_HOLDER_FAILURE = 'UNLINK_ALL_BIN_FROM_HOLDER_FAILURE';
