/** 
 * REDUX action type constant
*/

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_INFO_FETCHED = 'USER_INFO_FETCHED';
export const STATION_ACTIVATE_SUCCESS = 'STATION_ACTIVATE_SUCCESS';
export const STATION_ACTIVATE_ERROR = 'STATION_ACTIVATE_ERROR';
export const STATION_CURRENT_UNFINISH_TASK_FETCHED = 'STATION_CURRENT_UNFINISH_TASK_FETCHED';
export const AT_STATION_POD_LAYOUT_INFO_FETCHED = 'AT_STATION_POD_LAYOUT_INFO_FETCHED';
export const COMING_PODS_FETCHED = 'COMING_PODS_FETCHED';